name: Deployment to Heroku
on:
  push:
    branches:
      - release
jobs:
  deploy_to_heroku:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout src
      uses: actions/checkout@v2
    - name: Deploy
      uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "devbookapp" #Must be unique in Heroku
        heroku_email: ${{secrets.HEROKU_EMAIL}}